import { Geist, Geist_Mono, Roboto } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFont = Roboto({
  subsets: ['latin'],
  weight: ['300', '400','900'],
  variable: '--font-roboto'
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${robotoFont.variable}`}>
        <Script src={'https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js'} />
        {children}
      </body>
    </html>
  );
}
